#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from subc_ast.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "subc_ast.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ast.h"

void yyerror(const char *s);
int yylex();
extern int yydebug;
extern int yylineno;
extern char *yytext;
extern FILE *yyin; 

/* 全局AST根节点 */
ASTNode* ast_root = NULL;

#line 19 "subc_ast.y"
typedef union {
    int ival;
    float fval;
    char *sval;
    struct ast_node *ast;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	FLO	259
#define	ID	260
#define	INT	261
#define	FLOAT	262
#define	VOID	263
#define	IF	264
#define	ELSE	265
#define	WHILE	266
#define	RETURN	267
#define	INPUT	268
#define	PRINT	269
#define	ADD	270
#define	SUB	271
#define	MUL	272
#define	DIV	273
#define	MOD	274
#define	EQ	275
#define	ASG	276
#define	LT	277
#define	LE	278
#define	GT	279
#define	GE	280
#define	NE	281
#define	ANDAND	282
#define	OROR	283
#define	LPA	284
#define	RPA	285
#define	LBK	286
#define	RBK	287
#define	LBR	288
#define	RBR	289
#define	CMA	290
#define	SCO	291


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int FLO;
static const int ID;
static const int INT;
static const int FLOAT;
static const int VOID;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int RETURN;
static const int INPUT;
static const int PRINT;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int MOD;
static const int EQ;
static const int ASG;
static const int LT;
static const int LE;
static const int GT;
static const int GE;
static const int NE;
static const int ANDAND;
static const int OROR;
static const int LPA;
static const int RPA;
static const int LBK;
static const int RBK;
static const int LBR;
static const int RBR;
static const int CMA;
static const int SCO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,FLO=259
	,ID=260
	,INT=261
	,FLOAT=262
	,VOID=263
	,IF=264
	,ELSE=265
	,WHILE=266
	,RETURN=267
	,INPUT=268
	,PRINT=269
	,ADD=270
	,SUB=271
	,MUL=272
	,DIV=273
	,MOD=274
	,EQ=275
	,ASG=276
	,LT=277
	,LE=278
	,GT=279
	,GE=280
	,NE=281
	,ANDAND=282
	,OROR=283
	,LPA=284
	,RPA=285
	,LBK=286
	,RBK=287
	,LBR=288
	,RBR=289
	,CMA=290
	,SCO=291


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::FLO=259;
const int YY_parse_CLASS::ID=260;
const int YY_parse_CLASS::INT=261;
const int YY_parse_CLASS::FLOAT=262;
const int YY_parse_CLASS::VOID=263;
const int YY_parse_CLASS::IF=264;
const int YY_parse_CLASS::ELSE=265;
const int YY_parse_CLASS::WHILE=266;
const int YY_parse_CLASS::RETURN=267;
const int YY_parse_CLASS::INPUT=268;
const int YY_parse_CLASS::PRINT=269;
const int YY_parse_CLASS::ADD=270;
const int YY_parse_CLASS::SUB=271;
const int YY_parse_CLASS::MUL=272;
const int YY_parse_CLASS::DIV=273;
const int YY_parse_CLASS::MOD=274;
const int YY_parse_CLASS::EQ=275;
const int YY_parse_CLASS::ASG=276;
const int YY_parse_CLASS::LT=277;
const int YY_parse_CLASS::LE=278;
const int YY_parse_CLASS::GT=279;
const int YY_parse_CLASS::GE=280;
const int YY_parse_CLASS::NE=281;
const int YY_parse_CLASS::ANDAND=282;
const int YY_parse_CLASS::OROR=283;
const int YY_parse_CLASS::LPA=284;
const int YY_parse_CLASS::RPA=285;
const int YY_parse_CLASS::LBK=286;
const int YY_parse_CLASS::RBK=287;
const int YY_parse_CLASS::LBR=288;
const int YY_parse_CLASS::RBR=289;
const int YY_parse_CLASS::CMA=290;
const int YY_parse_CLASS::SCO=291;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		99
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 291 ? yytranslate[x] : 49)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     7,     8,    11,    17,    27,    29,    31,    33,
    37,    38,    41,    46,    52,    56,    58,    62,    69,    75,
    83,    89,    92,    96,   101,   103,   105,   107,   112,   116,
   120,   124,   129,   133,   134,   136,   140,   144,   148,   152,
   156,   160,   164,   168
};

static const short yyrhs[] = {    38,
    43,     0,    38,    39,    36,     0,     0,    40,     5,     0,
    40,     5,    31,     3,    32,     0,    40,     5,    29,    41,
    30,    33,    38,    43,    34,     0,     6,     0,     7,     0,
     8,     0,    41,    42,    36,     0,     0,    40,     5,     0,
    40,     5,    31,    32,     0,    40,     5,    29,    40,    30,
     0,    43,    36,    44,     0,    44,     0,     5,    21,    45,
     0,     5,    33,    45,    34,    21,    45,     0,     9,    29,
    48,    30,    44,     0,     9,    29,    48,    30,    44,    10,
    44,     0,    11,    29,    48,    30,    44,     0,    12,    45,
     0,    33,    43,    34,     0,     5,    29,    46,    30,     0,
     5,     0,     4,     0,     3,     0,     5,    31,    45,    32,
     0,    45,    15,    45,     0,    45,    17,    45,     0,    29,
    45,    30,     0,     5,    29,    46,    30,     0,    46,    47,
    35,     0,     0,    45,     0,     5,    31,    32,     0,     5,
    29,    30,     0,    45,    22,    45,     0,    45,    23,    45,
     0,    45,    20,    45,     0,    45,    26,    45,     0,    45,
    24,    45,     0,    45,    25,    45,     0,    45,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    65,    75,    80,    87,    95,   106,   120,   125,   130,   138,
   143,   150,   158,   166,   178,   183,   191,   199,   208,   214,
   221,   227,   232,   237,   248,   253,   258,   263,   271,   278,
   285,   290,   301,   306,   313,   318,   325,   335,   342,   349,
   356,   363,   370,   377
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","FLO",
"ID","INT","FLOAT","VOID","IF","ELSE","WHILE","RETURN","INPUT","PRINT","ADD",
"SUB","MUL","DIV","MOD","EQ","ASG","LT","LE","GT","GE","NE","ANDAND","OROR",
"LPA","RPA","LBK","RBK","LBR","RBR","CMA","SCO","program","declaration_list",
"declaration","type_specifier","param_list","param","statement_list","statement",
"expression","arg_list","arg","condition",""
};
#endif

static const short yyr1[] = {     0,
    37,    38,    38,    39,    39,    39,    40,    40,    40,    41,
    41,    42,    42,    42,    43,    43,    44,    44,    44,    44,
    44,    44,    44,    44,    45,    45,    45,    45,    45,    45,
    45,    45,    46,    46,    47,    47,    47,    48,    48,    48,
    48,    48,    48,    48
};

static const short yyr2[] = {     0,
     2,     3,     0,     2,     5,     9,     1,     1,     1,     3,
     0,     2,     4,     5,     3,     1,     3,     6,     5,     7,
     5,     2,     3,     4,     1,     1,     1,     4,     3,     3,
     3,     4,     3,     0,     1,     3,     3,     3,     3,     3,
     3,     3,     3,     1
};

static const short yydefact[] = {     3,
     0,     0,     7,     8,     9,     0,     0,     0,     0,     0,
     0,     1,    16,     0,    34,     0,     0,     0,    27,    26,
    25,     0,    22,     0,     2,     4,     0,    17,     0,     0,
    44,     0,     0,    34,     0,     0,     0,     0,    23,    11,
     0,    15,    25,    24,    35,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    31,    29,    30,
     0,     0,    34,     0,    33,     0,    40,    38,    39,    42,
    43,    41,    19,    21,    32,    28,     0,     0,     0,     5,
    37,    36,    18,     0,     3,    12,    10,    20,     0,     0,
     0,     0,     0,    13,     6,    14,     0,     0,     0
};

static const short yydefgoto[] = {    97,
     1,    10,    11,    61,    79,    12,    13,    31,    56,    46,
    32
};

static const short yypact[] = {-32768,
    58,    53,-32768,-32768,-32768,   -26,   -21,    50,    14,   -23,
     9,   -16,-32768,    50,-32768,    50,    50,    50,-32768,-32768,
    -2,    50,    75,    59,-32768,    71,    14,    75,    47,   -13,
    84,    -6,     4,-32768,    50,    66,    50,    50,-32768,-32768,
    34,-32768,    74,-32768,    75,     3,    27,    50,    50,    50,
    50,    50,    50,    14,    14,    68,    43,-32768,    39,-32768,
    10,    29,    38,     7,-32768,    50,    75,    75,    75,    75,
    75,    75,   105,-32768,-32768,-32768,    45,    79,    49,-32768,
-32768,-32768,    75,    14,-32768,    82,-32768,-32768,    58,    81,
    62,    78,    86,-32768,-32768,-32768,   117,   118,-32768
};

static const short yypgoto[] = {-32768,
    35,-32768,   -55,-32768,-32768,    -9,   -22,    -7,   104,-32768,
   103
};


#define	YYLAST		121


static const short yytable[] = {    24,
    23,    37,    17,    38,    42,    78,    28,    18,    30,    19,
    20,    21,    25,    26,    36,     3,     4,     5,     2,    27,
    47,    45,     6,    54,     7,     8,    34,    57,    35,    59,
    60,    73,    74,    55,    93,    22,    62,    65,    82,    77,
    67,    68,    69,    70,    71,    72,     9,    66,    45,    19,
    20,    43,    19,    20,    21,    38,    57,    37,    83,    38,
    80,    88,     2,     3,     4,     5,     6,    81,     7,     8,
    19,    20,    43,    14,    76,    22,    44,    85,    22,    92,
    37,    15,    38,    86,    87,    16,     3,     4,     5,    37,
     9,    38,    39,    94,    27,    58,    22,    75,    37,    40,
    38,    41,    63,    48,    64,    49,    50,    51,    52,    53,
    90,    95,    91,    27,    84,    96,    98,    99,    29,    89,
    33
};

static const short yycheck[] = {     9,
     8,    15,    29,    17,    27,    61,    14,    29,    16,     3,
     4,     5,    36,     5,    22,     6,     7,     8,     5,    36,
    34,    29,     9,    30,    11,    12,    29,    35,    31,    37,
    38,    54,    55,    30,    90,    29,     3,    35,    32,    30,
    48,    49,    50,    51,    52,    53,    33,    21,    56,     3,
     4,     5,     3,     4,     5,    17,    64,    15,    66,    17,
    32,    84,     5,     6,     7,     8,     9,    30,    11,    12,
     3,     4,     5,    21,    32,    29,    30,    33,    29,    89,
    15,    29,    17,     5,    36,    33,     6,     7,     8,    15,
    33,    17,    34,    32,    36,    30,    29,    30,    15,    29,
    17,    31,    29,    20,    31,    22,    23,    24,    25,    26,
    29,    34,    31,    36,    10,    30,     0,     0,    15,    85,
    18
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 66 "subc_ast.y"
{
          yyval.ast = create_ast_node(PROGRAM_NODE);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
          ast_root = yyval.ast;
      ;
    break;}
case 2:
#line 76 "subc_ast.y"
{
          yyval.ast = yyvsp[-2].ast;
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 3:
#line 81 "subc_ast.y"
{
          yyval.ast = create_ast_node(DECL_LIST_NODE);
      ;
    break;}
case 4:
#line 88 "subc_ast.y"
{
          yyval.ast = create_ast_node(VAR_DECL_NODE);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[0].sval);
          add_ast_child(yyval.ast, id_node);
      ;
    break;}
case 5:
#line 96 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARRAY_DECL_NODE);
          add_ast_child(yyval.ast, yyvsp[-4].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-3].sval);
          add_ast_child(yyval.ast, id_node);
          ASTNode* size_node = create_ast_node(NUM_EXPR_NODE);
          set_int_value(size_node, yyvsp[-1].ival);
          add_ast_child(yyval.ast, size_node);
      ;
    break;}
case 6:
#line 107 "subc_ast.y"
{
          yyval.ast = create_ast_node(FUNC_DECL_NODE);
          add_ast_child(yyval.ast, yyvsp[-8].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-7].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-5].ast);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 7:
#line 121 "subc_ast.y"
{
          yyval.ast = create_ast_node(TYPE_SPEC_NODE);
          set_type_value(yyval.ast, INT);
      ;
    break;}
case 8:
#line 126 "subc_ast.y"
{
          yyval.ast = create_ast_node(TYPE_SPEC_NODE);
          set_type_value(yyval.ast, FLOAT);
      ;
    break;}
case 9:
#line 131 "subc_ast.y"
{
          yyval.ast = create_ast_node(TYPE_SPEC_NODE);
          set_type_value(yyval.ast, VOID);
      ;
    break;}
case 10:
#line 139 "subc_ast.y"
{
          yyval.ast = yyvsp[-2].ast;
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 11:
#line 144 "subc_ast.y"
{
          yyval.ast = create_ast_node(PARAM_LIST_NODE);
      ;
    break;}
case 12:
#line 151 "subc_ast.y"
{
          yyval.ast = create_ast_node(PARAM_NODE);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[0].sval);
          add_ast_child(yyval.ast, id_node);
      ;
    break;}
case 13:
#line 159 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARRAY_PARAM_NODE);
          add_ast_child(yyval.ast, yyvsp[-3].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-2].sval);
          add_ast_child(yyval.ast, id_node);
      ;
    break;}
case 14:
#line 167 "subc_ast.y"
{
          yyval.ast = create_ast_node(FUNC_PARAM_NODE);
          add_ast_child(yyval.ast, yyvsp[-4].ast);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-3].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 15:
#line 179 "subc_ast.y"
{
          yyval.ast = yyvsp[-2].ast;
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 16:
#line 184 "subc_ast.y"
{
          yyval.ast = create_ast_node(STMT_LIST_NODE);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 17:
#line 192 "subc_ast.y"
{
          yyval.ast = create_ast_node(ASSIGN_STMT_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-2].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 18:
#line 200 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARRAY_ASSIGN_STMT_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-5].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-3].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 19:
#line 209 "subc_ast.y"
{
          yyval.ast = create_ast_node(IF_STMT_NODE);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 20:
#line 215 "subc_ast.y"
{
          yyval.ast = create_ast_node(IF_ELSE_STMT_NODE);
          add_ast_child(yyval.ast, yyvsp[-4].ast);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 21:
#line 222 "subc_ast.y"
{
          yyval.ast = create_ast_node(WHILE_STMT_NODE);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 22:
#line 228 "subc_ast.y"
{
          yyval.ast = create_ast_node(RETURN_STMT_NODE);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 23:
#line 233 "subc_ast.y"
{
          yyval.ast = create_ast_node(COMPOUND_STMT_NODE);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 24:
#line 238 "subc_ast.y"
{
          yyval.ast = create_ast_node(CALL_STMT_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-3].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 25:
#line 249 "subc_ast.y"
{
          yyval.ast = create_ast_node(ID_EXPR_NODE);
          set_string_value(yyval.ast, yyvsp[0].sval);
      ;
    break;}
case 26:
#line 254 "subc_ast.y"
{
          yyval.ast = create_ast_node(FLOAT_EXPR_NODE);
          set_float_value(yyval.ast, yyvsp[0].fval);
      ;
    break;}
case 27:
#line 259 "subc_ast.y"
{
          yyval.ast = create_ast_node(NUM_EXPR_NODE);
          set_int_value(yyval.ast, yyvsp[0].ival);
      ;
    break;}
case 28:
#line 264 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARRAY_ACCESS_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-3].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 29:
#line 272 "subc_ast.y"
{
          yyval.ast = create_ast_node(BINARY_EXPR_NODE);
          set_op_value(yyval.ast, ADD);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 30:
#line 279 "subc_ast.y"
{
          yyval.ast = create_ast_node(BINARY_EXPR_NODE);
          set_op_value(yyval.ast, MUL);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 31:
#line 286 "subc_ast.y"
{
          yyval.ast = create_ast_node(PAREN_EXPR_NODE);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 32:
#line 291 "subc_ast.y"
{
          yyval.ast = create_ast_node(CALL_EXPR_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-3].sval);
          add_ast_child(yyval.ast, id_node);
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 33:
#line 302 "subc_ast.y"
{
          yyval.ast = yyvsp[-2].ast;
          add_ast_child(yyval.ast, yyvsp[-1].ast);
      ;
    break;}
case 34:
#line 307 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARG_LIST_NODE);
      ;
    break;}
case 35:
#line 314 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARG_NODE);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 36:
#line 319 "subc_ast.y"
{
          yyval.ast = create_ast_node(ARRAY_ARG_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-2].sval);
          add_ast_child(yyval.ast, id_node);
      ;
    break;}
case 37:
#line 326 "subc_ast.y"
{
          yyval.ast = create_ast_node(FUNC_ARG_NODE);
          ASTNode* id_node = create_ast_node(ID_EXPR_NODE);
          set_string_value(id_node, yyvsp[-2].sval);
          add_ast_child(yyval.ast, id_node);
      ;
    break;}
case 38:
#line 336 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, LT);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 39:
#line 343 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, LE);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 40:
#line 350 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, EQ);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 41:
#line 357 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, NE);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 42:
#line 364 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, GT);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 43:
#line 371 "subc_ast.y"
{
          yyval.ast = create_ast_node(RELATIONAL_CONDITION_NODE);
          set_op_value(yyval.ast, GE);
          add_ast_child(yyval.ast, yyvsp[-2].ast);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
case 44:
#line 378 "subc_ast.y"
{
          yyval.ast = create_ast_node(CONDITION_NODE);
          add_ast_child(yyval.ast, yyvsp[0].ast);
      ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 384 "subc_ast.y"


void yyerror(const char *s) {
    fprintf(stderr, "Error: %s at line %d: %s\n", s, yylineno, yytext);
}

int main(int argc, char **argv) {
    if (argc > 1) {
        FILE *file = fopen(argv[1], "r");
        if (!file) {
            fprintf(stderr, "Cannot open file %s\n", argv[1]);
            return 1;
        }
        yyin = file;
    }
    
    int result = yyparse();
    
    if (result == 0 && ast_root != NULL) {
        printf("\n===== 抽象语法树 (AST) =====\n\n");
        print_ast_tree(ast_root, 0);
        printf("\n========================\n");
        
        // 释放AST内存
        free_ast_tree(ast_root);
    } else {
        printf("Parsing failed or no AST generated.\n");
    }
    
    return result;
}