60
START ID NUM _FLOS FLO ADD MUL LT LE ASG EQ LPA RPA LBK RBK LBR RBR CMA SCO _I IF _E _EL _ELS ELSE _W _WH _WHI _WHIL WHILE _R _RE _RET _RETU _RETUR RETURN _IN INT _INP _INPU INPUT _P _PR _PRI _PRIN PRINT _V _VO _VOI VOID _F _FL _FLO _FLOA FLOAT SKIP _CMT CMT MCMT _EMCMT

START

57
ID ID 
NUM NUM
FLO FLO
ADD ADD
MUL MUL
LT ROP
LE ROP
ASG ASG
EQ ROP
LPA LPA
RPA RPA
LBK LBK
RBK RBK
LBR LBR
RBR RBR
CMA CMA
SCO SCO
_I ID
IF IF
_E ID
_EL ID
_ELS ID
ELSE ELSE
_W ID
_WH ID
_WHI ID
_WHIL ID
WHILE WHILE
_R ID
_RE ID
_RET ID
_RETU ID
_RETUR ID
RETURN RETURN
_IN ID
INT INT
_INP ID
_INPU ID
INPUT INPUT
_P ID
_PR ID
_PRI ID
_PRIN ID
PRINT PRINT
_V ID
_VO ID
_VOI ID
VOID VOID
_F ID
_FL ID
_FLO ID
_FLOA ID
FLOAT FLOAT
SKIP SKIP
CMT SKIP
MCMT SKIP
_EMCMT SKIP
 
108
START [abcdghjklmnoqstuxyzABCDEFGHIJKLMNOPQRSTUVWXYZ] ID
START i _I
_I f IF
IF [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_I n _IN
_I [abcdeghijklmopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_IN p _INP
_IN t INT
_IN [abcdefghijklmnoqrsuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_INP u _INPU
_INP [abcdefghijklmnopqrstvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_INPU t INPUT
_INPU [abcdefghijklmnopqrsuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
INPUT [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START e _E
_E l _EL
_E [abcdefghijkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_EL s _ELS
_EL [abcdefghijklmnopqrtuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_ELS e ELSE
_ELS [abcdfghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
ELSE [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START w _W
_W h _WH
_W [abcdefgijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_WH i _WHI
_WH [abcdefghjklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_WHI l _WHIL 
_WHI [abcdefghijkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_WHIL e WHILE
_WHIL [abcdfghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
WHILE [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START r _R
_R e _RE
_R [abcdfghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_RE t _RET
_RE [abcdefghijklmnopqrsuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_RET u _RETU
_RET [abcdefghijklmnopqrstvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_RETU r _RETUR
_RETU [abcdefghijklmnopqstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_RETUR n RETURN
_RETUR [abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
RETURN [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START p _P
_P r _PR
_P [abcdefghijklmnopqstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_PR i _PRI
_PR [abcdefghjklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_PRI n _PRIN
_PRI [abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_PRIN t PRINT
_PRIN [abcdefghijklmnopqrsuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
PRINT [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START v _V
_V o _VO
_V [abcdefghijklmnpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_VO i _VOI
_VO [abcdefghjklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_VOI d VOID
_VOI [abcefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
VOID [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START f _F
_F l _FL
_F [abcdefghijkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_FL o _FLO
_FL [abcdefghijklmnpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_FLO a _FLOA
_FLO [bcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
_FLOA t FLOAT
_FLOA [abcdefghijklmnopqrsuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
FLOAT [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
START [0123456789] NUM
START \+ ADD
START - SUB
START \* MUL
START < LT
START = ASG
START \( LPA
START \) RPA
START \[ LBK
START \] RBK
START \{ LBR
START \} RBR
START , CMA
START ; SCO
START \. _FLOS
ID [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789] ID
ADD [0123456789] NUM
SUB [0123456789] NUM
ADD \. _FLOS
SUB \. _FLOS
NUM [0123456789] NUM
NUM \. FLO
_FLOS [0123456789] FLO
FLO [0123456789] FLO
LT = LE
ASG = EQ
START [\s] SKIP
START [\n\r] SKIP
START \/ _CMT
_CMT \/ CMT
CMT [^\n\r] CMT
CMT [\n\r] SKIP
_CMT \* MCMT
MCMT [^*] MCMT
MCMT \* _EMCMT
_EMCMT [^/] MCMT
_EMCMT \/ SKIP